/** @type {import('tailwindcss').Config} */

/**
 * Warna direferensikan lewat CSS variables yang didefinisikan di src/index.css
 * (:root = skema terang, .dark = skema gelap dari blok colors-dark di
 * design-system.md). Format nilai: channel RGB tanpa prefiks, dipakai sebagai
 * rgb(var(--c-*) / <alpha-value>) agar modifier opacity (/10, /20, dst.) tetap
 * berfungsi.
 */
const token = (name) => `rgb(var(--c-${name}) / <alpha-value>)`

export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    screens: {
      tablet: '600px',
      desktop: '1024px',
    },
    extend: {
      colors: {
        surface: token('surface'),
        'surface-dim': token('surface-dim'),
        'surface-bright': token('surface-bright'),
        'surface-container-lowest': token('surface-container-lowest'),
        'surface-container-low': token('surface-container-low'),
        'surface-container': token('surface-container'),
        'surface-container-high': token('surface-container-high'),
        'surface-container-highest': token('surface-container-highest'),
        'on-surface': token('on-surface'),
        'on-surface-variant': token('on-surface-variant'),
        'inverse-surface': token('inverse-surface'),
        'inverse-on-surface': token('inverse-on-surface'),
        outline: token('outline'),
        'outline-variant': token('outline-variant'),
        'surface-tint': token('surface-tint'),
        primary: token('primary'),
        'on-primary': token('on-primary'),
        'primary-container': token('primary-container'),
        'on-primary-container': token('on-primary-container'),
        'inverse-primary': token('inverse-primary'),
        secondary: token('secondary'),
        'on-secondary': token('on-secondary'),
        'secondary-container': token('secondary-container'),
        'on-secondary-container': token('on-secondary-container'),
        tertiary: token('tertiary'),
        'on-tertiary': token('on-tertiary'),
        'tertiary-container': token('tertiary-container'),
        'on-tertiary-container': token('on-tertiary-container'),
        error: token('error'),
        'on-error': token('on-error'),
        'error-container': token('error-container'),
        'on-error-container': token('on-error-container'),
        success: token('success'),
        'success-container': token('success-container'),
        warning: token('warning'),
        'warning-container': token('warning-container'),
        info: token('info'),
        'info-container': token('info-container'),
        'primary-fixed': token('primary-fixed'),
        'primary-fixed-dim': token('primary-fixed-dim'),
        'on-primary-fixed': token('on-primary-fixed'),
        'on-primary-fixed-variant': token('on-primary-fixed-variant'),
        'secondary-fixed': token('secondary-fixed'),
        'secondary-fixed-dim': token('secondary-fixed-dim'),
        'on-secondary-fixed': token('on-secondary-fixed'),
        'on-secondary-fixed-variant': token('on-secondary-fixed-variant'),
        'tertiary-fixed': token('tertiary-fixed'),
        'tertiary-fixed-dim': token('tertiary-fixed-dim'),
        'on-tertiary-fixed': token('on-tertiary-fixed'),
        'on-tertiary-fixed-variant': token('on-tertiary-fixed-variant'),
        background: token('background'),
        'on-background': token('on-background'),
        'surface-variant': token('surface-variant'),
        // Warna status kelas via CSS token — dark-mode aware
        'navy-slate': '#0f172a',
        'status-offline': '#10b981',
        'status-online': '#3b82f6',
        'status-hybrid': '#8b5cf6',
        'status-combined': '#f59e0b',
        // Semantic status-kelas tokens (K1/K2/HB/GBK/SYS)
        'status-k1':        token('status-k1'),
        'status-k1-bg':     token('status-k1-bg'),
        'status-k1-border': token('status-k1-border'),
        'status-k2':        token('status-k2'),
        'status-k2-bg':     token('status-k2-bg'),
        'status-k2-border': token('status-k2-border'),
        'status-hb':        token('status-hb'),
        'status-hb-bg':     token('status-hb-bg'),
        'status-hb-border': token('status-hb-border'),
        'status-gbk':       token('status-gbk'),
        'status-gbk-bg':    token('status-gbk-bg'),
        'status-gbk-border':token('status-gbk-border'),
        'status-sys':       token('status-sys'),
        'status-sys-bg':    token('status-sys-bg'),
        'status-sys-border':token('status-sys-border'),
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        schedule: '1rem',
      },
      spacing: {
        xs: '4px',
        base: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        'sidebar-width': '280px',
        'container-max': '1280px',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"Fira Code"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
        brand: ['"Space Grotesk"', 'sans-serif'],
        space: ['"Space Grotesk"', 'sans-serif'],
        marker: ['"Permanent Marker"', 'cursive', 'sans-serif'],
        handwriting: ['"Permanent Marker"', 'cursive', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.025em', fontWeight: '800' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['22px', { lineHeight: '30px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'title-lg': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'title-md': ['17px', { lineHeight: '26px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'title-sm': ['15px', { lineHeight: '22px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '500' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'body-xs': ['12px', { lineHeight: '18px', fontWeight: '500' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '700' }],
      },
      boxShadow: {
        'level-1':
          '0 1px 2px rgb(0 0 0 / 0.06), 0 1px 3px rgb(0 0 0 / 0.08)',
        'level-2': '0 12px 32px rgb(0 0 0 / 0.08)',
        'level-3': '0 8px 24px rgb(0 0 0 / 0.14)',
      },
    },
  },
  plugins: [],
}
